### ISSUE TITLE
Would it be possible to add support for silencing phone alarms from the watch

### ISSUE THREAD

**Issue by dcacklam** [blunden/DoNotDisturbSync#11] opened 2023-12-24 04:50 UTC
Another 'missing' feature from the old wear os, is the ability to remote-control the phone's alarm-clock function.

So if your phone was in the kitchen & you're in the living room, and an alarm goes off... You could tap something on your watch to dismiss the alarm on your phone.

Would it be possible for this app to do 'that' in a similar way to how it does DnD sync?

**Comment by blunden** [comment] 2024-02-02 15:04
Can't you already do this if you use Google's alarm app on both devices? I don't know for sure, but I would assume so.

I don't know if there is a way to tell the alarm app to dismiss an alarm that is currently ringing. It also seems a bit like feature creep, but if there is an API to dismiss the alarm, it's would likely be possible.

**Comment by dcacklam** [comment] 2024-02-02 19:30
No. At least not for the 3+ versions of WearOS.
It used to be on WearOS 1 and 2 that (in the same sense that turning DND on
or off on the watch did it on the phone too) an alarm set on the phone
would ring on both devices and could be dismissed from either device.

Now? They are separate.

**Comment by blunden** [comment] 2024-02-03 12:27
The problem is that there needs to be an API to have a service be woken up when the alarm is ringing, and also to dismiss them.

**Comment by blunden** [comment] 2024-03-19 12:01
I can silence my phone alarms (Google Alarms app) from my Galaxy Watch4 Classic already. Tried it recently. I don't think that is a Samsung specific feature.

Either way, I consider this out of scope of this app so I'll close this issue. :)

**Closed as completed by blunden** 2024-03-19 12:01 UTC
